Set node version to v8.6.0
Required for building tensorflow-binding, since with lower node version
(< v8.6.0) it gives: `error: use of undeclared identifier 'NAPI_AUTO_LENGTH'`.